name: YOH-DropMagnet
version: '${project.version}'
main: fr.yohorchestre.itemmagnet.ItemMagnetPlugin
api-version: '1.21'
authors: [ Antigravity ]
description: Aimant à item avec filtres et protection anti-dupli.
depend: []
softdepend: [ WorldGuard ]

commands:
  magnet:
    description: Commande principale pour l'aimant à item
    usage: /magnet <give|reload>
    permission: itemmagnet.admin
  magnetlog:
    description: Voir les logs d'un aimant spécifique
    usage: /magnetlog <ID>
    permission: itemmagnet.admin.logs
